import type { PyrolaChatMode } from '@/types/pyrola/pyrola-settings'

const READ_ONLY_TOOLS = [
  'read_file',
  'grep',
  'glob_files',
  'list_dir',
  'git_status',
  'git_diff',
  'git_log',
  'git_branch',
  'lsp',
  'diagnostics',
  'run_terminal',
  'terminal_output',
  'stop_terminal',
  'web_fetch',
  'web_search',
  'load_skill',
  'ask_user',
  'call_mcp_tool',
  'get_mcp_tools',
] as const

const ORCHESTRATOR_TOOLS = [
  'read_file',
  'list_dir',
  'grep',
  'glob_files',
  'git_status',
  'git_diff',
  'git_log',
  'git_branch',
  'lsp',
  'diagnostics',
  'web_fetch',
  'load_skill',
  'ask_user',
  'call_mcp_tool',
  'get_mcp_tools',
  'create_plan',
  'update_plan_todo',
  'spawn_subagent',
] as const

export const MODE_TOOL_ALLOWLIST: Record<PyrolaChatMode, string[]> = {
  ask: [...READ_ONLY_TOOLS],
  plan: [
    ...READ_ONLY_TOOLS,
    'create_plan',
    'update_plan_todo',
  ],
  studio: [
    ...READ_ONLY_TOOLS,
    'create_plan',
    'update_plan_todo',
    'write_studio_artifact',
  ],
  agent: [
    'read_file',
    'write_file',
    'edit_file',
    'apply_patch',
    'delete_file',
    'move_file',
    'grep',
    'glob_files',
    'list_dir',
    'git_status',
    'git_diff',
    'git_log',
    'git_branch',
    'git_checkout',
    'git_branch_create',
    'git_commit',
    'lsp',
    'diagnostics',
    'run_terminal',
    'terminal_output',
    'stop_terminal',
    'web_fetch',
    'web_search',
    'load_skill',
    'ask_user',
    'call_mcp_tool',
    'get_mcp_tools',
    'create_plan',
    'update_plan_todo',
    'write_studio_artifact',
    'spawn_subagent',
  ],
  orchestrator: [...ORCHESTRATOR_TOOLS],
}

export const filterToolsByMode = <T extends { name: string }>(
  mode: PyrolaChatMode,
  tools: T[],
): T[] => {
  const allow = new Set(MODE_TOOL_ALLOWLIST[mode])
  return tools.filter((tool) => allow.has(tool.name))
}
