import type { PyrolaChatMode } from '@/types/pyrola/pyrola-settings'

export const MODE_TOOL_ALLOWLIST: Record<PyrolaChatMode, string[]> = {
  ask: [
    'read_file',
    'grep',
    'glob_files',
    'list_dir',
    'git_status',
    'git_diff',
    'git_log',
    'git_branch',
    'lsp',
    'web_fetch',
    'web_search',
    'load_skill',
    'ask_user',
    'call_mcp_tool',
  ],
  plan: [
    'read_file',
    'grep',
    'glob_files',
    'list_dir',
    'git_status',
    'git_diff',
    'git_log',
    'git_branch',
    'lsp',
    'web_fetch',
    'web_search',
    'load_skill',
    'ask_user',
    'call_mcp_tool',
    'create_plan',
    'update_plan_todo',
  ],
  studio: [
    'read_file',
    'grep',
    'glob_files',
    'list_dir',
    'git_status',
    'git_diff',
    'git_log',
    'git_branch',
    'lsp',
    'web_fetch',
    'web_search',
    'load_skill',
    'ask_user',
    'call_mcp_tool',
    'create_plan',
    'update_plan_todo',
    'write_studio_artifact',
  ],
  agent: [
    'read_file',
    'write_file',
    'edit_file',
    'apply_patch',
    'grep',
    'glob_files',
    'list_dir',
    'git_status',
    'git_diff',
    'git_log',
    'git_branch',
    'lsp',
    'run_terminal',
    'web_fetch',
    'web_search',
    'load_skill',
    'ask_user',
    'call_mcp_tool',
    'create_plan',
    'update_plan_todo',
    'write_studio_artifact',
    'spawn_subagent',
  ],
}

export const filterToolsByMode = <T extends { name: string }>(
  mode: PyrolaChatMode,
  tools: T[],
): T[] => {
  const allow = new Set(MODE_TOOL_ALLOWLIST[mode])
  return tools.filter((tool) => allow.has(tool.name))
}
